spring.application.name=itic
server.port=8085
server.forward-headers-strategy=native

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:room_reservation_system}}
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:api_user}
spring.datasource.password=${DB_PASSWORD:1234}

# IMPORTANT: Activar l'execució dels scripts SQL
#spring.sql.init.mode=always

# SQL logging
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# URLs Configuration
app.frontend.url=${FRONTEND_URL:http://localhost:8081}
app.backend.url=${BACKEND_URL:http://localhost:8085}

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${app.backend.url}/login/oauth2/code/google

# AWS Cognito Configuration
aws.cognito.region=${AWS_COGNITO_REGION:eu-west-1}
aws.cognito.userPoolId=${AWS_COGNITO_USER_POOL_ID}
aws.cognito.clientId=${AWS_COGNITO_CLIENT_ID}
# JWT Configuration
app.jwt.secret=${JWT_SECRET:vY29tZS10by1teS1hdzNzb21lLWFnZW5kYS1hcGktcHJvamVjdC13aXRoLWp3dC10b2tlbnM=}